### PR TITLE
(feat) add typescript types to New Relic related components

### PR DESCRIPTION
**Pull request by christianvuerings**
# Changes

* Fixes 2 TypeScript errors in pages/_document.tsx

# Notes

* I tried including `@types/newrelic` but those seem outdated since `newrelic.agent` and the `allowTransactionlessInjection` option on `getBrowserTimingHeader` do not yet exist.

### CODE REVIEW

**Comment by christianvuerings** [comment]
@matewilk would you be able to take a look?

**Comment by matewilk** [comment]
Hey @christianvuerings,

Thanks for the PR, 

I'll take a look as soon as I can, hopefully by the end of the week.
I'll also include some global type definitions for the NR Browser Agent methods.

**Comment by matewilk** [comment]
Hey @christianvuerings,

I've added the `@types/newrelic` package and overrode some methods (the package is out of date as you've mentioned so it's a temp solution for the time being)
I also added types for the New Relic browser agent under `/types/global.d.ts`

Let me know if you need anything else before I merge.

**Comment by christianvuerings** [comment]
Looks great, thank you!

**Pull request merged**
